backend:
  name: github
  repo: cannandev/jekyll-uswds-netlify
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, es, fr]
  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - label: Posts
    name: posts
    folder: _posts/
    create: true
    slug: "{{locales.locale}}/{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    i18n: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "post",
          i18n: "duplicate",
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "MMMM D, YYYY",
          date_format: "MMMM D, YYYY",
          time_format: false,
          i18n: "duplicate",
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
